### ISSUE TITLE
Stuck at first search query

### ISSUE THREAD

**Issue by MrPancake** [fabiospampinato/cliflix#34] opened 2020-01-17 22:43 UTC
Whenever i try to watch something, it gets stuck on the first search query (1337x)

![cliflix_sad](https://user-images.githubusercontent.com/8533671/72651271-260b5f80-3983-11ea-8912-dda25eb49dcf.gif)

**Comment by fabiospampinato** [comment] 2020-01-17 23:13
Duplicate of #22

**Closed by fabiospampinato** 2020-01-17 23:13 UTC
