### ISSUE TITLE
Tilde expansion

### ISSUE THREAD

**Issue by HP4k1h5** [fabiospampinato/cliflix#39] opened 2020-07-29 13:02 UTC
if you use a `~` to set `downloads.path` in the config, cliflix will download to its local node_modules subdirectory.

example config: `{"downloads": {"path": "~/Downloads"}}`

Expected result: downloads to be in `$HOME/Downloads`
Actual result: downloads to `path/to/global_node_modules/cliflix/~/Downloads`

i believe a special handler is needed when options are loaded and `_.merge()`'d

https://github.com/fabiospampinato/cliflix/blob/0dc09b90acc570375b8dbf40278fe35c4f815ed4/src/config.ts#L104

id be happy to submit a pr if you are accepting

**Comment by fabiospampinato** [comment] 2020-09-12 22:58
Sure, PR welcome

**Comment by fabiospampinato** [comment] 2020-09-12 23:03
Duplicate of https://github.com/fabiospampinato/cliflix/issues/38

**Closed by fabiospampinato** 2020-09-12 23:03 UTC
Labels: enhancement, help wanted
