### ISSUE TITLE
Stuck on searching

### ISSUE THREAD

**Issue by HairyCap** [fabiospampinato/cliflix#28] opened 2019-01-04 05:00 UTC
Stuck on Waiting for "1337x"...   and Ctrl+C can't exit, my network can go to 1337x site and search. I try to change the provider, but it's the same.

**Comment by HairyCap** [comment] 2019-01-04 17:05
yes, but all stuck there and the terminal has no response too.
I try run it on git bash and result is like this,
some of it say No torrents found, some just Cannot read property 'get' of undefined

$ cliflix
? What do you want to watch? naruto
? What do you want to watch? naruto
- Waiting for "ThePirateBay"...
No torrents found via "ThePirateBay"
- Waiting for "ExtraTorrent"...

Cannot read property 'get' of undefined

$ cliflix
? What do you want to watch? naruto
? What do you want to watch? naruto
- Waiting for "ThePirateBay"...
No torrents found via "ThePirateBay"
- Waiting for "ExtraTorrent"...

Cannot read property 'get' of undefined

$ cliflix
? What do you want to watch? naruto
? What do you want to watch? naruto
- Waiting for "1337x"...

Cannot read property 'get' of undefined

$ cliflix
? What do you want to watch? naruto
? What do you want to watch? naruto
- Waiting for "TorrentProject"...
No torrents found via "TorrentProject"
- Waiting for "Torrentz2"...

Cannot read property 'get' of undefined

$ cliflix
? What do you want to watch? naruto
? What do you want to watch? naruto
- Waiting for "Rarbg"...

Cannot read property 'get' of undefined

**Comment by fabiospampinato** [comment] 2019-01-04 17:09
> Cannot read property 'get' of undefined

That looks like a bug, it would be awesome if you could submit a PR for this.

**Comment by HairyCap** [comment] 2019-01-04 19:33
I want to, but I need to learn TypeScript first🤣.

**Comment by fabiospampinato** [comment] 2019-01-04 19:37
If you were looking for a reason to learn it now you have one ;)

**Comment by fabiospampinato** [comment] 2020-01-17 23:13
Duplicate of #22

**Closed by fabiospampinato** 2020-01-17 23:13 UTC
Labels: bug
